# Devices Cleanup Script | [https://guns.lol/inso.vs]
# Automatic optimization tool that efficiently removes phantom devices (non-present hardware)
# from the system registry to eliminate performance degradation, driver conflicts, and hardware
# initialization delays. Targets obsolete USB, Plug-and-Play, and ghost devices with error code 45
# that accumulate over time and negatively impact system responsiveness and peripheral reactivity.
# The script preserves devices with assigned CPU affinity settings to maintain user optimizations.
# Usage: Run the script with administrator privileges, review detected phantom devices, confirm removal.
# Benefits: Improved system performance and responsiveness, faster device initialization, enhanced
# peripheral reactivity (mouse, keyboard, audio), reduced driver conflicts, freed system resources,
# cleaner registry, optimized boot times, and elimination of COM port collisions.
# Ideal for: comp players, and users with frequent external device connections.

# For Personal use only. Modification/redistribution prohibited.
# Official source: [https://guns.lol/inso.vs] | Last Updated: 2026-01-27
# Replicates DeviceCleanupTool by Uwe Sieber (https://www.uwe-sieber.de)

$insoptiWindow=$Host.UI.RawUI;$Host.UI.RawUI.WindowTitle="Device Cleanup Tool Script | Removes unused devices to optimize system & device performance (like DeviceCleanupTool - https://www.majorgeeks.com/files/details/device_cleanup_tool.html)";$Host.UI.RawUI.BackgroundColor="Black";Clear-Host
if(-not((New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator))){Write-Host "restart" -ForegroundColor blue -NoNewline;" the script as administrator..";Start-Process -FilePath "powershell" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs;exit};Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
function Get-Timestamp{$time=Get-Date -Format "HH:mm:ss";Write-Host " [" -NoNewline -ForegroundColor Blue;Write-Host "$time" -NoNewline -ForegroundColor DarkGray;Write-Host "]" -NoNewline -ForegroundColor Blue}
function insopti{$insoptidots=@("",".","..","..");$insoptimsgText=" processing";Clear-Host;for($i=0;$i -lt 8;$i++){$insoptitext=$insoptidots[$i % $insoptidots.Length];Write-Host -NoNewline "`r";Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Green;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host -NoNewline "$insoptimsgText$insoptitext";Start-Sleep -Milliseconds 222};[System.Console]::SetCursorPosition(0,[System.Console]::CursorTop);Write-Host(" " * [System.Console]::WindowWidth) -NoNewline;[System.Console]::SetCursorPosition(0,[System.Console]::CursorTop)
function Test-DeviceHasAffinity{param([string]$InstanceId);try{$deviceName=$InstanceId -replace '.*\\([^\\]+)$','$1';$affinityPaths=@("HKLM:\SYSTEM\CurrentControlSet\Enum\$InstanceId\Affinity","HKLM:\SYSTEM\CurrentControlSet\Enum\$InstanceId\Device Parameters\Interrupt Management\Affinity Policy");$irqPath="HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl";foreach($path in $affinityPaths){if(Test-Path $path){$affinity=Get-ItemProperty -Path $path -ErrorAction SilentlyContinue;if($affinity.DefaultAffinity -or $affinity.AssignmentSetOverride -or $affinity.DevicePolicy){return $true}}};$msiPath="HKLM:\SYSTEM\CurrentControlSet\Enum\$InstanceId\Device Parameters\Interrupt Management\MessageSignaledInterruptProperties";if(Test-Path $msiPath){$msiProps=Get-ItemProperty -Path $msiPath -ErrorAction SilentlyContinue;if($msiProps.MessageNumberLimit -or $msiProps.MSISupported){$affinityPath="HKLM:\SYSTEM\CurrentControlSet\Enum\$InstanceId\Device Parameters\Interrupt Management\Affinity Policy";if(Test-Path $affinityPath){$affinityProps=Get-ItemProperty -Path $affinityPath -ErrorAction SilentlyContinue;if($affinityProps.DevicePolicy -eq 4 -or $affinityProps.AssignmentSetOverride){return $true}}}};return $false}catch{return $false}}
$insopti_Devices=Get-PnpDevice|Where-Object{$_.Status -eq "Unknown"};if($insopti_Devices.Count -eq 0){Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Green;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " No devices need to be removed." -ForegroundColor blue;return}
$devicesWithAffinity=@();$devicesToRemove=@();foreach($device in $insopti_Devices){if(Test-DeviceHasAffinity -InstanceId $device.InstanceId){$devicesWithAffinity+=$device}else{$devicesToRemove+=$device}}
if($devicesWithAffinity.Count -gt 0){Show-DevicesCleanupHeader;Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "/" -NoNewline -ForegroundColor Yellow;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Protected devices (CPU affinity configured):" -ForegroundColor darkgray;$devicesWithAffinity|ForEach-Object{Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "≡" -NoNewline -ForegroundColor darkgreen;Write-Host "]" -NoNewline -ForegroundColor blue;Write-Host " $($_.Name) - InstanceId: $($_.InstanceId)" -ForegroundColor Darkgray}}
if($devicesToRemove.Count -gt 0){Write-Host "";Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor White;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Devices need to be removed:" -ForegroundColor green;$devicesToRemove|ForEach-Object{Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "×" -NoNewline -ForegroundColor Red;Write-Host "]" -NoNewline -ForegroundColor blue;Write-Host " $($_.Name) - InstanceId: $($_.InstanceId)"};Write-Host "";Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "?" -NoNewline -ForegroundColor Cyan;Write-Host "]" -ForegroundColor blue -NoNewline;$confirmation=Read-Host " Confirm removal of $($devicesToRemove.Count) device(s)? (Y/N)";if($confirmation -eq 'Y' -or $confirmation -eq 'y'){foreach($device in $devicesToRemove){Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor White;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Removal of: " -ForegroundColor Blue -NoNewline;Write-Host "$($device.Name).." -ForegroundColor Darkgray -NoNewline;try{pnputil.exe /remove-device $device.InstanceId|Out-Null;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Green;Write-Host "]" -NoNewline -ForegroundColor blue;Write-Host " Successfully removed." -ForegroundColor Green}catch{Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "×" -NoNewline -ForegroundColor Red;Write-Host "]" -NoNewline -ForegroundColor blue;Write-Host " Error during removal: $_" -ForegroundColor Red}}}else{Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "×" -NoNewline -ForegroundColor Yellow;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Removal cancelled by user." -ForegroundColor Yellow}}else{Write-Host "";Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Green;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " No devices neeed to be remove (all have CPU affinity configured)." -ForegroundColor blue}
Write-Host "";Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "i" -NoNewline -ForegroundColor Cyan;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Summary: " -NoNewline -ForegroundColor blue;Write-Host "$($devicesWithAffinity.Count) protected, $($devicesToRemove.Count) removed." -ForegroundColor White;Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Green;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Cleaning completed." -ForegroundColor DarkGreen}
function Show-DevicesCleanupHeader{Clear-Host;Write-Host "`n";Write-Host "                                Removes Unused & Unknown Devices to Optimize System Latency." -ForegroundColor DarkGray;Write-Host "                    :::::::::   ::::::::::  :::     :::  :::::::::::  ::::::::   ::::::::::  ::::::::  " -ForegroundColor Blue;Write-Host "                    :+:    :+:  :+:         :+:     :+:      :+:     :+:    :+:  :+:        :+:    :+: " -ForegroundColor Blue;Write-Host "                    +:+    +:+  +:+         +:+     +:+      +:+     +:+         +:+        +:+        " -ForegroundColor Blue;Write-Host "                    +#+    +:+  +#++:++#    +#+     +:+      +#+     +#+         +#++:++#   +#++:++#++ " -ForegroundColor Blue;Write-Host "                    +#+    +#+  +#+          +#+   +#+       +#+     +#+         +#+               +#+ " -ForegroundColor Blue;Write-Host "                    #+#    #+#  #+#           #+#+#+#        #+#     #+#    #+#  #+#        #+#    #+# " -ForegroundColor Blue;Write-Host "                    #########   ##########      ###      ###########  ########   ##########  ########  " -ForegroundColor Blue;Write-Host "";Write-Host "                                                [Cleanup One Click Script]" -ForegroundColor Blue;Write-Host "`n"}3
function insoptistart{Show-DevicesCleanupHeader;Write-Host "                  For personal use only. " -ForegroundColor Gray -NoNewline;Write-Host "Modifying" -ForegroundColor Red -NoNewline;Write-Host "," -ForegroundColor White -NoNewline;Write-Host " copying" -ForegroundColor Red -NoNewline;Write-Host "," -ForegroundColor White -NoNewline;Write-Host " or" -ForegroundColor White -NoNewline;Write-Host " redistributing" -ForegroundColor Red -NoNewline;Write-Host " this script is " -ForegroundColor Gray -NoNewline;Write-Host "prohibited" -ForegroundColor Red -NoNewline;Write-Host "." -ForegroundColor Gray;Write-Host "                  This script must be downloaded only from the official source: " -ForegroundColor Gray -NoNewline;Write-Host "https://guns.lol/inso.vs" -ForegroundColor DarkGray;Write-Host "";Write-Host "             This script scans and removes unused or obsolete devices from the system using native PowerShell" -ForegroundColor Gray;Write-Host "              and pnputil.exe. Its goal is to clean up driver leftovers, unknown devices, and ghost entries." -ForegroundColor Gray;Write-Host "           This helps to improve responsiveness, reduce resource usage, and prevent hardware conflicts. It also" -ForegroundColor Gray;Write-Host "                 helps to reduce device initialization delays and makes peripherals respond more smoothly." -ForegroundColor Gray;Write-Host "";Write-Host "                 Noticeably improves the " -ForegroundColor Gray -NoNewline;Write-Host "feeling and reactivity" -ForegroundColor Cyan -NoNewline;Write-Host " of mouse, keyboard, and other peripherals" -ForegroundColor Gray;Write-Host "        instantly after cleanup, depending on the number of unnecessary devices previously registered on the system." -ForegroundColor Gray;Write-Host "                  Ideal for systems with many USB or Plug-and-Play devices frequently added or removed." -ForegroundColor Gray;Write-Host "";Write-Host "                                           [" -NoNewline -ForegroundColor Gray;Write-Host "+" -NoNewline -ForegroundColor green;Write-Host "]" -NoNewline -ForegroundColor Gray;Write-Host " Press any key to start cleanup.`n";[void][System.Console]::ReadKey($true);insopti}
function insoptiexitmainmenu{Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Green;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Enter your choice:`n" -ForegroundColor DarkGray;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "1" -NoNewline -ForegroundColor White;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Exit";Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "2" -NoNewline -ForegroundColor White;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Go to Discord";$insoptiChoice=Read-Host " >>";switch($insoptiChoice){"1"{insoptiquit}"2"{insoptiDiscord}default{Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "/" -NoNewline -ForegroundColor Yellow;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Invalid choice" -ForegroundColor Yellow;Start-Sleep -Seconds 1;insoptiexitmainmenu}}}
function insoptiDiscord{param([string]$insoptiURL="https://guns.lol/inso.vs");try{Start-Process -FilePath $insoptiURL;Write-Host "";Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Yellow;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Guns profile page has been opened successfully." -ForegroundColor Green}catch{Write-Host "";Get-Timestamp;Write-Host " [" -ForegroundColor Green -NoNewline;Write-Host "×" -NoNewline -ForegroundColor Red;Write-Host "]" -NoNewline;Write-Host " Error opening the page: $_" -ForegroundColor Red};Start-Sleep -Seconds 2;insoptiquit}
function insoptiquit{Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "+" -NoNewline -ForegroundColor Green;Write-Host "]" -NoNewline -ForegroundColor blue;Write-Host " Press any key to quit." -ForegroundColor blue;Write-Host " https://guns.lol/inso.vs" -ForegroundColor DarkGray;[void][System.Console]::ReadKey($true);insoptiquit2}
function insoptiquit2{Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "/" -NoNewline -ForegroundColor Yellow;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host " Script aborted by user." -ForegroundColor Yellow;Start-Sleep -Milliseconds 999;$insoptiLoadingMessage=" Closing the script";$insoptiDotCount=0;while($insoptiDotCount -lt 5){Get-Timestamp;Write-Host " [" -NoNewline -ForegroundColor blue;Write-Host "/" -NoNewline -ForegroundColor Yellow;Write-Host "]" -ForegroundColor blue -NoNewline;Write-Host "$insoptiLoadingMessage$('.' * ($insoptiDotCount + 1))" -NoNewline;Start-Sleep -Milliseconds 188;Clear-Host;$insoptiDotCount++};exit};insoptistart;insoptiexitmainmenu
#https://guns.lol/inso.vs